#+TITLE: Julia for the Average Joe Coder
#+STYLE: <link rel="stylesheet" href="./css/style.css"/>
I don't do technical computing or anything of that sort but Julia is my new favorite language.
I have successfully replaced Python with Julia as my go-to language of choice. And boy am I a happy person.
Julia is a very pleasant langugage.

This is a tutorial in the same vein as tutorials to general purpose dynamic programming/scripting languages like Python or Ruby. This could be the tutorial you have been missing.

* Why Julia?
All the reasons you'd use python apply here. Language wise, in my opinion, Julia is strictly better than Python. [[http://julialang.org/blog/2012/02/why-we-created-julia/][Why we created Julia]].

* Getting Started

* Syntax and Basics

** Variables

** Functions

** Types

** Arrays

** Dictionaries

** Sets

** More Data Structures

* Multiple dispatch > OOP
** Methods

** OOP trivialized
*** Polymorphism
*** Inheritance

* Scripting
** Command line

** File IO

** Regular expressions

* Macros
